import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// 1. IMPORT TOASTER
import { Toaster } from 'react-hot-toast';
import AuthGuard from '@/components/AuthGuard'; // Import it

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Time Tracker App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // ADD suppressHydrationWarning HERE vvv
    <html lang="en" suppressHydrationWarning> 
      <body className={inter.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <AuthGuard />
        {children}
      </body>
    </html>
  );
}